name: Software Quality Documentation
description: CSC-640 Software Quality Principles and Best Practices
url: "https://islerm2-nku.github.io/CSC-640-MI-Docs.github.io"
baseurl: "/CSC-640-MI-Docs.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Site settings
author: CSC-640 Team
email: your-email@example.com

# Navigation
header_pages:
  - requirements.html
  - tech-stack.html
  - modular-code.html
  - testing.html
  - deployment.html
  - additional-topics.html